name: locate_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_map: ^6.1.0
  hooks_riverpod: ^2.4.9
  latlong2: ^0.9.0
  location: ^5.0.3
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true
